In [33]:
import numpy as np  # type: ignore
import tester


In [34]:
a = np.array([
    [2, -1, 1, 1],
    [1, 2, -1, -1],
    [-1, 2, 2, 2],
    [1, -1, 2, 1]
], dtype = np.dtype(float) )

In [35]:
b = np.array([6, 3, 14, 8], dtype = np.dtype(float))

In [36]:
tester.test_matrix(a, b)

 All tests passed


find the determinant of matrix A and solution vector

In [37]:
determinant = np.linalg.det(a) #determinant
vector = np.linalg.solve(a, b) #solution vector
print(f'determinant of the matrix: {determinant:.2f}')
print(f'solution vector of the matrix: {vector}')

determinant of the matrix: -17.00
solution vector of the matrix: [2. 3. 4. 1.]


In [38]:
def multiplyRow(matrix, row_num, mulitple_val):
    matrix_new = matrix.copy()
    matrix_new[row_num] = matrix_new[row_num] * mulitple_val
    return matrix_new

def addRows(matrix, row_num1, row_num2, multiple_val):
    matrix_new = matrix.copy()
    matrix_new[row_num2] = matrix_new[row_num1] * multiple_val + matrix_new[row_num2]
    return matrix_new

def swapRows(matrix, row_num1, row_num2):
    matrix_new = matrix.copy()
    matrix_new[[row_num1 , row_num2]] = matrix_new[[row_num2 , row_num1]]
    return matrix_new

In [39]:
matrix_updatedBymultiplication = multiplyRow(a, 2, 5)
print(f'matrix\'s 3rd row  is multiplied by 5:\n {matrix_updatedBymultiplication}')

matrix_updatedByAdd = addRows(a, 1, 3, 3)
print(f'matrix\'s 4th row  is added by itself and multiple of 3 of 2nd row:\n {matrix_updatedByAdd}')

matrix_updatedBySwap = swapRows(a, 0 , 2)
print(f'matrix\'s 1st row is swapped by 3rd:\n {matrix_updatedBySwap}')



matrix's 3rd row  is multiplied by 5:
 [[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-5. 10. 10. 10.]
 [ 1. -1.  2.  1.]]
matrix's 4th row  is added by itself and multiple of 3 of 2nd row:
 [[ 2. -1.  1.  1.]
 [ 1.  2. -1. -1.]
 [-1.  2.  2.  2.]
 [ 4.  5. -1. -2.]]
matrix's 1st row is swapped by 3rd:
 [[-1.  2.  2.  2.]
 [ 1.  2. -1. -1.]
 [ 2. -1.  1.  1.]
 [ 1. -1.  2.  1.]]


row reduction


In [83]:
def rowReduction(matrix, vector):
    a = np.hstack((matrix, vector.reshape((4, 1))))
    a_ref = swapRows(a, 0, 1)
    a_ref = addRows(a_ref, 0, 1, -2)
    a_ref = addRows(a_ref, 0, 2, 1)
    a_ref = addRows(a_ref, 0, 3, -1)
    a_ref = addRows(a_ref, 2, 3, 1)
    a_ref = swapRows(a_ref, 1, 3)
    a_ref = addRows(a_ref, 2, 3, 1)
    a_ref = addRows(a_ref, 1, 2, -4)
    a_ref = addRows(a_ref, 1, 3, 1)
    a_ref = addRows(a_ref, 3, 2, 2)
    a_ref = addRows(a_ref, 2, 3, -8)
    a_ref = multiplyRow(a_ref, 3, -1/17)
   
    return a_ref

In [84]:
a_test = rowReduction(a, b)
print(a_test)

[[ 1.  2. -1. -1.  3.]
 [ 0.  1.  4.  3. 22.]
 [ 0.  0.  1.  3.  7.]
 [-0. -0. -0.  1.  1.]]


finding solution using the row reduction matrix

In [85]:
x4 = 1
x3 = a_test[2,4] - a_test[2,3] * x4
x2 = a_test[1,4] - a_test[1,3] * x4 - a_test[1,2] * x3
x1 = a_test[0,4] - a_test[0,3] * x4 - a_test[0,2] * x3 - a_test[0,1] * x2
print(x1, x2, x3, x4)

2.0 3.0 4.0 1


reducing using same above to form diagonal 



In [102]:
def diagonalForm(a_ref):
    a_ref = addRows(a_ref, 1, 0, -2)
    a_ref = addRows(a_ref, 2, 0, 9)
    a_ref = addRows(a_ref, 2, 1, -4)
    a_ref = addRows(a_ref, 3, 0, -20)
    a_ref = addRows(a_ref, 3, 1, 9)
    a_ref = addRows(a_ref, 3, 2, -3)
    return a_ref

In [103]:
diag = diagonalForm(a_test)
print(diag)

[[ 1.  0.  0.  0.  2.]
 [ 0.  1.  0.  0.  3.]
 [ 0.  0.  1.  0.  4.]
 [-0. -0. -0.  1.  1.]]
